# Generated by Django 5.2.11 on 2026-02-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='app_user',
        ),
    ]
