services:
  - type: web
    name: construction-cms
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn construction_cms.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: construction-db
          property: connectionString

databases:
  - name: construction-db
    plan: free
    databaseName: construction_db
    user: postgres
