# Generated by Django 5.2.11 on 2026-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
